CREATE TABLE IF NOT EXISTS otp (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `otp_value` VARCHAR(10) NOT NULL,
    `email` varchar(255) DEFAULT NULL,
    `expiry_time` DATETIME NOT NULL,
    `is_verified` BOOLEAN NOT NULL DEFAULT FALSE,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `unique_email` (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;